### ISSUE TITLE
Hi there! Just download the sample,then 'ionic serve and... nothing happens 

### ISSUE THREAD

**Issue by srlopez** [CloudBoost/sample-ionic-social-network#1]
the explorer bring up but nothing happens.
May i have to do any think?

Please i need a README.md

**Comment by nawazdhandala** [comment]
@srlopez Sure. Let us look into it. We'll also have Readme in the repo. :)

**Comment by blacksector** [comment]
@srlopez 
I know this is old but hopefully it can help others
Make sure you:
1. Have run `npm install` in the directory where you extracted this
2. Make sure you have ionic framework installed

After that ionic serve should work just fine.
